In [24]:
import os
from logging import getLogger

import torch
import pandas as pd
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
from gensim.models.keyedvectors import KeyedVectors
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
import japanize_matplotlib

logger = getLogger()

src_lang = 'fr'
tgt_lang = 'ja'
mid_lang = 'en'

s_t_path = f'debug_file/debug/evaluate_{src_lang}_{mid_lang}_{tgt_lang.upper()}/best_mapping_{src_lang}2{tgt_lang}.t7'
s_m_path = f'debug_file/debug/evaluate_{src_lang}_{mid_lang}_{tgt_lang.upper()}/best_mapping_{src_lang}2{mid_lang}.t7'
m_t_path = f'debug_file/debug/evaluate_{src_lang}_{mid_lang}_{tgt_lang.upper()}/best_mapping_{mid_lang}2{tgt_lang}.t7'

s_t_reload = torch.from_numpy(torch.load(s_t_path))
s_m_reload = torch.from_numpy(torch.load(s_m_path))
m_t_reload = torch.from_numpy(torch.load(m_t_path))



wikivec_src = KeyedVectors.load_word2vec_format(f"data/fasttext-vectors/{src_lang}wiki_300d.txt", limit=200000)
wikivec_tgt = KeyedVectors.load_word2vec_format(f"data/fasttext-vectors/{tgt_lang}wiki_300d.txt", limit=200000)
wikivec_mid = KeyedVectors.load_word2vec_format(f"data/fasttext-vectors/{mid_lang}wiki_300d.txt", limit=200000)

In [239]:
f_e_j_iden = {880: 0, 923: 0, 962: 0, 1006: 1, 1087: 0, 1093: 1, 1305: 1, 1478: 0, 2551: 1, 2579: 0, 2600: 0, 2638: 0, 2663: 1, 2675: 1, 2688: 1, 2760: 0, 2783: 1, 2786: 0, 2788: 0, 2815: 0, 2863: 0, 2904: 0, 2907: 0, 2928: 0, 2941: 0, 2975: 0, 2988: 1, 2996: 0, 2998: 0, 3021: 0, 3028: 0, 3049: 1, 3064: 0, 3074: 1, 3105: 1, 3123: 0, 3153: 0, 3173: 0, 3196: 0, 3197: 0, 3219: 0, 3222: 0, 3229: 0, 3232: 0, 3235: 0, 3236: 0, 3263: 0, 3289: 0, 3293: 0, 3308: 1, 3309: 0, 3338: 0, 3342: 0, 3344: 0, 3368: 0, 3376: 0, 3377: 1, 3389: 1, 3391: 0, 3418: 1, 3419: 1, 3433: 0, 3444: 0, 3445: 0, 3450: 1, 3460: 0, 3481: 0, 3491: 1, 3494: 0, 3495: 0, 3507: 0, 3520: 1, 3549: 0, 3550: 0, 3553: 0, 3575: 0, 3588: 1, 3589: 1, 3593: 1, 3602: 0, 3634: 1, 3638: 1, 3644: 1, 3653: 1, 3658: 0, 3676: 0, 3688: 0, 3696: 0, 3698: 0, 3704: 0, 3708: 0, 3714: 0, 3718: 0, 3723: 0, 3726: 1, 3749: 1, 3753: 0, 3756: 1, 3765: 0, 3768: 0, 3769: 0, 3770: 0, 3772: 1, 3792: 0, 3793: 1, 3797: 0, 3798: 1, 3806: 0, 3811: 1, 3822: 0, 3829: 0, 3843: 0, 3849: 0, 3851: 0, 3853: 1, 3870: 0, 3874: 1, 3878: 0, 3883: 0, 3890: 1, 3906: 0, 3912: 1, 3922: 0, 3927: 0, 3928: 0, 3931: 0, 3934: 0, 3939: 1, 3943: 0, 3963: 0, 3975: 1, 3980: 1, 3983: 1, 3984: 0, 3994: 0, 3997: 1, 3998: 0, 4001: 1, 4004: 1, 4008: 0, 4010: 0, 4011: 0, 4015: 0, 4017: 1, 4018: 0, 4021: 1, 4024: 0, 4030: 1, 4031: 1, 4034: 0, 4039: 0, 4062: 1, 4065: 0, 4073: 1, 4075: 0, 4083: 0, 4085: 1, 4098: 0, 4100: 0, 4108: 1, 4116: 0, 4125: 0, 4126: 1, 4130: 1, 4132: 0, 4142: 0, 4146: 1, 4148: 0, 4150: 0, 4156: 1, 4157: 1, 4168: 0, 4174: 0, 4183: 0, 4198: 0, 4206: 1, 4210: 0, 4219: 1, 4229: 0, 4231: 0, 4234: 0, 4237: 0, 4245: 0, 4250: 0, 4261: 0, 4271: 1, 4280: 1, 4314: 1, 4315: 0, 4331: 0, 4332: 0, 4335: 0, 4349: 0, 4357: 0, 4358: 0, 4373: 1, 4384: 0, 4388: 1, 4406: 0, 4413: 0, 4415: 0, 4417: 1, 4422: 1, 4423: 0, 4424: 0, 4427: 1, 4438: 1, 4445: 0, 4448: 0, 4459: 0, 4462: 0, 4465: 1, 4478: 1, 4485: 0, 4488: 1, 4489: 1, 4492: 1, 4496: 1, 4497: 0, 4500: 1, 4509: 0, 4513: 0, 4518: 0, 4521: 0, 4525: 0, 4533: 0, 4536: 0, 4552: 1, 4559: 0, 4560: 1, 4563: 0, 4577: 0, 4580: 1, 4587: 0, 4588: 0, 4592: 0, 4598: 1, 4604: 0, 4606: 0, 4609: 0, 4617: 0, 4622: 1, 4625: 1, 4629: 1, 4635: 0, 4636: 0, 4642: 0, 4643: 1, 4644: 0, 4653: 1, 4655: 1, 4656: 0, 4659: 0, 4664: 0, 4673: 1, 4678: 1, 4680: 1, 4691: 1, 4711: 0, 4714: 0, 4722: 1, 4728: 0, 4735: 0, 4736: 1, 4739: 1, 4741: 0, 4744: 0, 4746: 0, 4747: 1, 4754: 1, 4755: 0, 4759: 1, 4767: 0, 4768: 0, 4769: 0, 4777: 1, 4789: 0, 4791: 1, 4801: 1, 4804: 0, 4813: 0, 4815: 0, 4821: 0, 4831: 0, 4840: 1, 4867: 0, 4868: 1, 4880: 1, 4928: 1, 4929: 1, 4934: 1, 4944: 1, 4946: 0, 4948: 0, 4949: 0, 4954: 0, 4957: 0, 4963: 0, 4967: 0, 4974: 1, 4987: 0, 4988: 1, 4993: 1, 4997: 1, 5004: 1, 5006: 1, 5007: 1, 5009: 1, 5010: 0, 5013: 0, 5017: 0, 5021: 1, 5027: 0, 5030: 0, 5034: 0, 5037: 0, 5052: 0, 5053: 1, 5065: 1, 5070: 1, 5075: 1, 5082: 0, 5097: 0, 5105: 0, 5108: 0, 5115: 0, 5116: 1, 5119: 0, 5135: 1, 5144: 1, 5155: 0, 5158: 1, 5161: 0, 5163: 0, 5173: 0, 5181: 0, 5183: 1, 5185: 1, 5190: 0, 5192: 1, 5196: 0, 5199: 1, 5206: 0, 5210: 1, 5214: 0, 5215: 0, 5219: 0, 5227: 0, 5229: 0, 5231: 1, 5233: 0, 5240: 1, 5241: 0, 5252: 0, 5258: 0, 5267: 1, 5269: 0, 5275: 1, 5276: 0, 5284: 1, 5286: 1, 5287: 0, 5292: 1, 5298: 0, 5301: 0, 5310: 1, 5311: 0, 5313: 0, 5324: 0, 5328: 0, 5333: 0, 5341: 0, 5352: 0, 5355: 0, 5356: 0, 5378: 0, 5393: 0, 5398: 1, 5399: 0, 5401: 0, 5417: 1, 5426: 0, 5437: 0, 5439: 0, 5441: 0, 5450: 1, 5464: 1, 5466: 0, 5474: 0, 5477: 1, 5478: 0, 5483: 1, 5485: 0, 5497: 0, 5500: 0, 5502: 1, 5503: 1, 5504: 1, 5510: 1, 5518: 0, 5520: 0, 5521: 0, 5525: 0, 5532: 0, 5536: 0, 5539: 1, 5544: 1, 5548: 0, 5568: 0, 5575: 1, 5578: 0, 5581: 0, 5584: 0, 5587: 1, 5597: 0, 5607: 0, 5611: 1, 5613: 0, 5614: 0, 5626: 0, 5635: 1, 5637: 1, 5645: 1, 5647: 1, 5656: 1, 5658: 1, 5659: 0, 5662: 1, 5663: 0, 5664: 0, 5666: 1, 5667: 0, 5676: 0, 5679: 0, 5681: 0, 5682: 0, 5716: 0, 5717: 1, 5718: 1, 5724: 1, 5726: 1, 5728: 1, 5736: 1, 5739: 0, 5741: 0, 5755: 1, 5764: 1, 5766: 0, 5788: 0, 5793: 0, 5801: 0, 5808: 0, 5810: 0, 5819: 1, 5833: 1, 5836: 0, 5839: 1, 5840: 1, 5847: 0, 5849: 1, 5850: 1, 5853: 0, 5854: 1, 5866: 0, 5868: 1, 5874: 1, 5881: 1, 5886: 0, 5905: 1, 5910: 0, 5913: 0, 5921: 0, 5940: 1, 5942: 1, 5945: 0, 5946: 1, 5953: 0, 5959: 1, 5966: 0, 5970: 0, 5971: 1, 5977: 0, 5981: 1, 5991: 1, 5995: 1, 6002: 1, 6018: 0, 6019: 1, 6021: 0, 6023: 1, 6027: 0, 6034: 1, 6036: 1, 6037: 0, 6043: 1, 6048: 0, 6050: 1, 6059: 1, 6063: 1, 6065: 0, 6068: 1, 6070: 1, 6075: 0, 6087: 0, 6091: 0, 6094: 0, 6096: 0, 6097: 0, 6109: 1, 6110: 0, 6111: 0, 6115: 0, 6124: 0, 6126: 1, 6131: 0, 6140: 1, 6160: 0, 6170: 1, 6173: 0, 6179: 1, 6185: 0, 6188: 0, 6192: 1, 6193: 0, 6202: 1, 6204: 0, 6226: 0, 6229: 1, 6236: 0, 6241: 1, 6246: 0, 6248: 0, 6253: 1, 6254: 0, 6275: 0, 6287: 0, 6291: 1, 6294: 0, 6303: 0, 6310: 0, 6318: 0, 6323: 0, 6330: 1, 6338: 1, 6344: 1, 6354: 1, 6356: 1, 6365: 0, 6366: 0, 6370: 1, 6371: 0, 6373: 0, 6374: 0, 6377: 1, 6383: 0, 6396: 1, 6398: 1, 6419: 0, 6441: 0, 6444: 1, 6446: 0, 6458: 0, 6462: 0, 6485: 0, 6493: 0, 6516: 0, 6517: 1, 6523: 0, 6541: 0, 6548: 1, 6559: 1, 6564: 0, 6574: 0, 6581: 0, 6586: 0, 6594: 0, 6604: 1, 6609: 1, 6611: 1, 6623: 1, 6628: 0, 6637: 1, 6649: 0, 6650: 0, 6660: 1, 6671: 1, 6673: 1, 6680: 0, 6685: 0, 6706: 0, 6712: 0, 6714: 0, 6716: 0, 6743: 1, 6751: 0, 6754: 0, 6765: 0, 6770: 0, 6776: 1, 6784: 1, 6793: 1, 6810: 1, 6835: 1, 6846: 1, 6887: 1, 6911: 0, 6912: 1, 6925: 1, 6927: 0, 6934: 1, 6943: 0, 6946: 0, 6956: 1, 6966: 1, 6976: 0, 6982: 0, 6992: 1, 7005: 1, 7013: 1, 7016: 1, 7017: 1, 7022: 1, 7028: 1, 7032: 1, 7033: 0, 7041: 0, 7042: 0, 7048: 0, 7060: 1, 7064: 0, 7068: 1, 7070: 1, 7071: 0, 7083: 1, 7087: 1, 7092: 0, 7093: 1, 7094: 0, 7096: 0, 7099: 0, 7105: 0, 7112: 1, 7117: 0, 7118: 0, 7131: 0, 7140: 1, 7150: 1, 7151: 0, 7169: 1, 7173: 0, 7179: 0, 7188: 0, 7189: 0, 7198: 0, 7204: 0, 7221: 0, 7225: 0, 7238: 0, 7239: 0, 7263: 0, 7271: 0, 7278: 1, 7304: 0, 7308: 1, 7314: 1, 7349: 0, 7354: 0, 7367: 0, 7385: 0, 7391: 1, 7400: 1, 7405: 0, 7418: 0, 7429: 1, 7435: 0, 7451: 1, 7452: 1, 7473: 1, 7475: 0, 7486: 0, 7487: 0, 7499: 0, 7515: 1, 7534: 0, 7535: 0, 7553: 1, 7576: 0, 7578: 0, 7608: 0, 7610: 1, 7616: 1, 7618: 0, 7625: 1, 7644: 1, 7645: 0, 7654: 1, 7662: 0, 7663: 1, 7671: 0, 7680: 0, 7716: 1, 7741: 0, 7762: 0, 7794: 0, 7815: 1, 7840: 0, 7842: 0, 7851: 0, 7853: 0, 7877: 0, 7883: 0, 7888: 0, 7911: 0, 7915: 0, 7918: 1, 7927: 0, 7931: 1, 7949: 1, 7957: 1, 7960: 0, 7961: 1, 8016: 0, 8061: 1, 8085: 1, 8093: 1, 8135: 1, 8142: 1, 8163: 1, 8172: 0, 8182: 1, 8187: 1, 8206: 1, 8213: 1, 8214: 0, 8252: 1, 8254: 0, 8255: 0, 8272: 0, 8349: 1, 8367: 1, 8371: 0, 8391: 1, 8401: 1, 8420: 0, 8471: 0, 8472: 1, 8478: 0, 8493: 0, 8502: 0, 8507: 0, 8619: 0, 8620: 0, 8625: 0, 8647: 1, 8648: 1, 8649: 1, 8659: 1, 8669: 1, 8684: 1, 8721: 1, 8724: 1, 8727: 0, 8792: 0, 8820: 0, 8822: 0, 8823: 0, 8824: 0, 8840: 0, 8842: 1, 8848: 0, 8920: 1, 8935: 0, 8941: 0, 8960: 1, 8982: 0, 9013: 1, 9020: 1, 9053: 0, 9128: 0, 9131: 0, 9140: 0, 9149: 0, 9155: 0, 9169: 1, 9171: 0, 9180: 1, 9187: 0, 9189: 1, 9214: 1, 9225: 0, 9233: 1, 9235: 0, 9237: 0, 9244: 0, 9252: 0, 9293: 0, 9298: 1, 9360: 0, 9399: 0, 9423: 0, 9467: 0, 9472: 0, 9481: 0, 9488: 0, 9498: 0, 9511: 1, 9520: 0, 9534: 0, 9541: 1, 9548: 0, 9560: 0, 9563: 0, 9576: 0, 9578: 0, 9580: 0, 9606: 1, 9638: 0, 9653: 1, 9664: 0, 9683: 0, 9690: 1, 9720: 0, 9738: 1, 9740: 0, 9758: 0, 9768: 1, 9773: 1, 9780: 0, 9785: 1, 9789: 1, 9795: 1, 9809: 0, 9817: 0, 9821: 0, 9830: 0, 9869: 0, 9918: 0, 9926: 0, 9936: 0, 9948: 1, 9951: 0, 9963: 1, 9969: 1, 9999: 1, 10043: 0, 10086: 0, 10090: 0, 10202: 1, 10222: 1, 10231: 0, 10339: 1, 10374: 0, 10386: 1, 10388: 0, 10394: 0, 10399: 0, 10430: 0, 10484: 1, 10492: 1, 10620: 0, 10622: 0, 10640: 0, 10648: 0, 10655: 0, 10665: 1, 10703: 1, 10735: 1, 10759: 1, 10771: 0, 10787: 1, 10877: 0, 10909: 0, 10950: 0, 10970: 0, 10995: 0, 11015: 1, 11037: 1, 11069: 0, 11071: 1, 11097: 0, 11117: 1, 11123: 0, 11139: 0, 11162: 1, 11179: 1, 11180: 0, 11203: 0, 11211: 0, 11222: 0, 11228: 0, 11253: 0, 11269: 0, 11336: 0, 11373: 0, 11395: 1, 11411: 0, 11473: 0, 11484: 0, 11523: 0, 11645: 0, 11655: 0, 11663: 0, 11682: 0, 11684: 0, 11694: 1, 11696: 0, 11739: 0, 11806: 0, 11809: 1, 11875: 1, 11960: 1, 12008: 1, 12011: 0, 12015: 0, 12158: 0, 12205: 0, 12213: 1, 12237: 1, 12250: 1, 12251: 0, 12254: 0, 12286: 0, 12298: 0, 12308: 0, 12317: 0, 12318: 0, 12324: 1, 12373: 1, 12375: 1, 12407: 0, 12453: 0, 12467: 1, 12504: 0, 12526: 0, 12545: 1, 12647: 0, 12667: 1, 12720: 0, 12726: 1, 12779: 1, 12801: 0, 12854: 0, 12905: 0, 12937: 0, 12979: 1, 13008: 0, 13039: 0, 13044: 0, 13061: 0, 13074: 0, 13098: 1, 13099: 1, 13121: 0, 13134: 0, 13141: 0, 13146: 1, 13154: 0, 13158: 1, 13167: 0, 13170: 1, 13200: 0, 13209: 0, 13369: 0, 13464: 0, 13475: 1, 13506: 1, 13554: 1, 13597: 1, 13670: 0, 13676: 0, 13697: 0, 13785: 0, 13814: 0, 13817: 0, 13838: 1, 13955: 0, 13965: 0, 14110: 0, 14145: 0, 14146: 0, 14156: 0, 14169: 0, 14359: 0, 14406: 0, 14422: 0, 14456: 0, 14481: 1, 14495: 0, 14496: 0, 14505: 1, 14524: 0, 14555: 0, 14561: 1, 14576: 0, 14584: 1, 14591: 1, 14663: 0, 14729: 0, 14774: 0, 14783: 0, 14786: 0, 14788: 0, 14817: 0, 14958: 0, 14997: 0, 14998: 0, 15026: 0, 15038: 1, 15056: 0, 15061: 0, 15072: 0, 15107: 0, 15135: 0, 15183: 0, 15252: 1, 15262: 0, 15296: 1, 15305: 1, 15356: 1, 15372: 0, 15375: 1, 15394: 1, 15412: 0, 15426: 0, 15521: 0, 15550: 0, 15563: 0, 15605: 1, 15755: 0, 15867: 0, 15970: 0, 16003: 1, 16008: 0, 16028: 1, 16056: 0, 16067: 0, 16078: 1, 16116: 0, 16198: 0, 16222: 1, 16283: 1, 16297: 0, 16377: 1, 16438: 0, 16484: 0, 16517: 0, 16551: 0, 16578: 0, 16595: 0, 16606: 0, 16654: 0, 16750: 0, 16776: 0, 16790: 0, 16807: 1, 16829: 1, 16831: 1, 16833: 1, 16847: 0, 16879: 0, 16892: 0, 16983: 0, 17006: 0, 17012: 1, 17024: 0, 17174: 0, 17201: 0, 17269: 0, 17330: 0, 17342: 1, 17382: 0, 17385: 0, 17408: 0, 17436: 1, 17473: 1, 17605: 0, 17704: 0, 17743: 1, 17858: 0, 17897: 0, 17909: 0, 17961: 0, 18082: 1, 18096: 0, 18147: 0, 18201: 0, 18343: 0, 18498: 0, 18501: 0, 18562: 0, 18572: 0, 18623: 0, 18685: 0, 18752: 1, 18777: 0, 18784: 0, 18802: 0, 18858: 0, 18862: 0, 18880: 0, 18891: 0, 18905: 0, 18910: 0, 18964: 1, 18981: 0, 19154: 1, 19155: 0, 19194: 0, 19254: 0, 19266: 0, 19273: 0, 19286: 0, 19325: 0, 19378: 0, 19418: 0, 19437: 0, 19508: 0, 19613: 0, 19669: 1, 19693: 0, 19843: 1, 19855: 0, 19859: 0, 19865: 1, 19926: 0, 19981: 0, 20004: 0, 20026: 0, 20037: 0, 20043: 1, 20058: 1, 20150: 0, 20204: 1, 20235: 0, 20262: 0, 20282: 1, 20382: 0, 20424: 0, 20453: 0, 20471: 0, 20495: 0, 20534: 0, 20663: 0, 20709: 0, 20759: 1, 20768: 0, 20772: 0, 20848: 0, 20874: 0, 20897: 0, 20908: 0, 20930: 0, 20969: 1, 21024: 0, 21170: 0, 21236: 0, 21352: 0, 21359: 0, 21442: 0, 21481: 0, 21537: 0, 21643: 0, 21697: 0, 21701: 1, 21909: 0, 22010: 0, 22033: 0, 22157: 0, 22182: 1, 22225: 0, 22296: 0, 22399: 1, 22432: 0, 22592: 0, 22612: 1, 22631: 1, 22705: 1, 22764: 1, 22794: 0, 22816: 0, 22820: 1, 22896: 0, 23075: 0, 23105: 0, 23178: 0, 23242: 0, 23274: 0, 23305: 0, 23320: 0, 23453: 0, 23458: 0, 23552: 0, 23615: 0, 23690: 0, 23714: 0, 23882: 0, 24008: 0, 24076: 1, 24131: 0, 24161: 0, 24467: 0, 24587: 1, 24691: 0, 24877: 0, 24969: 0, 25151: 0, 25186: 0, 25357: 0, 25394: 0, 25398: 0, 25420: 0, 25535: 0, 25541: 0, 25620: 0, 25763: 0, 25851: 0, 25926: 0, 25938: 0, 25949: 0, 26133: 0, 26165: 0, 26218: 0, 26317: 1, 26349: 1, 26390: 0, 26695: 1, 26744: 0, 26843: 0, 27003: 0, 27284: 1, 27387: 0, 27431: 0, 27437: 0, 27479: 0, 27590: 0, 27625: 0, 27710: 0, 27880: 0, 27921: 0, 27924: 1, 27925: 0, 28189: 0, 28226: 0, 28342: 0, 28581: 0, 28617: 0, 28661: 0, 29025: 0, 29038: 0, 29040: 1, 29060: 1, 29256: 1, 29519: 0, 29558: 0, 29617: 0, 29845: 0, 29969: 0, 29970: 0, 30295: 0, 30305: 0, 30406: 0, 30421: 1, 30661: 0, 30698: 0, 31003: 0, 31168: 0, 31169: 0, 31329: 0, 31405: 0, 31448: 0, 31585: 0, 31606: 0, 31854: 1, 31928: 0, 31939: 0, 31997: 0, 32045: 0, 32101: 0, 32634: 1, 32636: 0, 33041: 0, 33678: 0, 33684: 0, 33794: 0, 33804: 0, 33981: 0, 34004: 0, 34175: 0, 34210: 0, 34219: 0, 34266: 0, 34578: 1, 34760: 0, 34797: 0, 34801: 0, 34933: 0, 34977: 0, 35029: 0, 35263: 0, 35270: 0, 35351: 1, 35424: 1, 35618: 0, 35820: 0, 35970: 0, 36120: 0, 36138: 0, 36337: 0, 36346: 0, 36415: 0, 36503: 0, 36558: 0, 37200: 0, 37536: 0, 38699: 0, 39208: 0, 39316: 0, 39358: 0, 39815: 0, 39853: 0, 40021: 0, 40280: 0, 40400: 0, 40645: 0, 40713: 0, 40901: 0, 41045: 1, 41302: 0, 41705: 0, 42790: 0, 42805: 0, 43074: 1, 43212: 0, 43229: 0, 43342: 0, 43620: 1, 43752: 0, 43828: 0, 44262: 0, 44964: 0, 45259: 0, 45595: 0, 45710: 0, 45938: 0, 46082: 1, 46201: 1, 46412: 0, 47847: 0, 48128: 0, 48342: 0, 48710: 0, 49130: 0, 49179: 0, 50076: 1, 50284: 0, 50332: 1, 50660: 0, 51552: 1, 52165: 0, 52302: 1, 52667: 0, 53056: 0, 53334: 1, 54337: 0, 54821: 0, 55333: 0, 55482: 1, 55489: 1, 55563: 0, 55711: 0, 56020: 0, 56269: 0, 56358: 0, 57392: 0, 57551: 0, 58149: 0, 58323: 1, 59825: 0, 59832: 1, 60106: 1, 60481: 0, 60824: 0, 60920: 0, 61257: 0, 61472: 0, 62422: 0, 64078: 0, 64692: 0, 64992: 0, 65366: 0, 66767: 0, 67493: 0, 67803: 0, 67928: 0, 68828: 0, 69294: 0, 69810: 0, 70066: 0, 70222: 0, 70664: 0, 71625: 1, 72072: 0, 72199: 0, 73670: 0, 74106: 1, 74883: 0, 75372: 0, 75527: 0, 76523: 0, 77248: 0, 77574: 0, 78706: 0, 81124: 0, 82342: 0, 82752: 0, 82954: 1, 84161: 0, 84488: 0, 85957: 1, 87431: 0, 87439: 0, 88412: 0, 89455: 0, 91438: 1, 95980: 0, 97745: 0, 98928: 0, 99321: 0, 99866: 0, 100623: 0, 101498: 0, 104659: 0, 108062: 0, 110424: 0, 112489: 0, 113966: 0, 125330: 0, 131156: 0, 132395: 0, 132652: 0, 138087: 0, 143765: 0, 148737: 0, 153791: 0, 157508: 0, 162767: 0, 163897: 0, 165682: 0, 166880: 0, 169515: 0, 170653: 0, 179140: 0, 189967: 0, 190087: 0, 194675: 0}
f_j_iden = {880: 0, 923: 0, 962: 0, 1006: 0, 1087: 0, 1093: 1, 1305: 1, 1478: 0, 2551: 0, 2579: 0, 2600: 0, 2638: 0, 2663: 1, 2675: 0, 2688: 1, 2760: 0, 2783: 1, 2786: 0, 2788: 0, 2815: 0, 2863: 0, 2904: 0, 2907: 0, 2928: 0, 2941: 0, 2975: 0, 2988: 0, 2996: 0, 2998: 0, 3021: 0, 3028: 0, 3049: 0, 3064: 0, 3074: 1, 3105: 1, 3123: 0, 3153: 0, 3173: 0, 3196: 0, 3197: 0, 3219: 0, 3222: 0, 3229: 0, 3232: 0, 3235: 0, 3236: 0, 3263: 0, 3289: 0, 3293: 0, 3308: 0, 3309: 0, 3338: 0, 3342: 0, 3344: 0, 3368: 0, 3376: 0, 3377: 0, 3389: 1, 3391: 0, 3418: 1, 3419: 1, 3433: 0, 3444: 0, 3445: 0, 3450: 1, 3460: 0, 3481: 0, 3491: 0, 3494: 0, 3495: 0, 3507: 0, 3520: 1, 3549: 1, 3550: 1, 3553: 0, 3575: 0, 3588: 1, 3589: 0, 3593: 1, 3602: 0, 3634: 0, 3638: 1, 3644: 1, 3653: 1, 3658: 0, 3676: 0, 3688: 0, 3696: 0, 3698: 0, 3704: 0, 3708: 0, 3714: 0, 3718: 0, 3723: 0, 3726: 0, 3749: 1, 3753: 0, 3756: 1, 3765: 0, 3768: 0, 3769: 0, 3770: 0, 3772: 1, 3792: 0, 3793: 0, 3797: 0, 3798: 1, 3806: 0, 3811: 0, 3822: 0, 3829: 0, 3843: 0, 3849: 1, 3851: 0, 3853: 0, 3870: 0, 3874: 1, 3878: 0, 3883: 1, 3890: 1, 3906: 0, 3912: 1, 3922: 0, 3927: 0, 3928: 0, 3931: 0, 3934: 0, 3939: 1, 3943: 1, 3963: 0, 3975: 0, 3980: 1, 3983: 1, 3984: 0, 3994: 0, 3997: 0, 3998: 1, 4001: 1, 4004: 1, 4008: 0, 4010: 0, 4011: 0, 4015: 0, 4017: 1, 4018: 1, 4021: 0, 4024: 0, 4030: 0, 4031: 1, 4034: 0, 4039: 0, 4062: 1, 4065: 0, 4073: 1, 4075: 0, 4083: 0, 4085: 1, 4098: 0, 4100: 0, 4108: 1, 4116: 0, 4125: 0, 4126: 1, 4130: 1, 4132: 0, 4142: 0, 4146: 1, 4148: 0, 4150: 0, 4156: 0, 4157: 1, 4168: 0, 4174: 1, 4183: 0, 4198: 0, 4206: 0, 4210: 0, 4219: 1, 4229: 0, 4231: 0, 4234: 0, 4237: 0, 4245: 0, 4250: 0, 4261: 0, 4271: 1, 4280: 1, 4314: 0, 4315: 0, 4331: 0, 4332: 0, 4335: 0, 4349: 0, 4357: 0, 4358: 0, 4373: 1, 4384: 0, 4388: 1, 4406: 0, 4413: 1, 4415: 0, 4417: 1, 4422: 0, 4423: 0, 4424: 0, 4427: 1, 4438: 1, 4445: 0, 4448: 0, 4459: 0, 4462: 0, 4465: 1, 4478: 0, 4485: 0, 4488: 1, 4489: 0, 4492: 1, 4496: 1, 4497: 0, 4500: 1, 4509: 0, 4513: 0, 4518: 0, 4521: 0, 4525: 0, 4533: 0, 4536: 0, 4552: 1, 4559: 1, 4560: 1, 4563: 0, 4577: 0, 4580: 1, 4587: 0, 4588: 0, 4592: 0, 4598: 0, 4604: 0, 4606: 0, 4609: 0, 4617: 0, 4622: 0, 4625: 1, 4629: 1, 4635: 0, 4636: 0, 4642: 0, 4643: 1, 4644: 0, 4653: 0, 4655: 1, 4656: 0, 4659: 0, 4664: 0, 4673: 1, 4678: 1, 4680: 1, 4691: 1, 4711: 0, 4714: 0, 4722: 0, 4728: 0, 4735: 0, 4736: 1, 4739: 1, 4741: 1, 4744: 0, 4746: 0, 4747: 0, 4754: 0, 4755: 0, 4759: 1, 4767: 0, 4768: 0, 4769: 0, 4777: 1, 4789: 0, 4791: 1, 4801: 1, 4804: 0, 4813: 1, 4815: 0, 4821: 0, 4831: 0, 4840: 1, 4867: 1, 4868: 1, 4880: 1, 4928: 1, 4929: 1, 4934: 1, 4944: 1, 4946: 0, 4948: 0, 4949: 0, 4954: 0, 4957: 0, 4963: 0, 4967: 0, 4974: 1, 4987: 0, 4988: 1, 4993: 1, 4997: 1, 5004: 1, 5006: 0, 5007: 1, 5009: 0, 5010: 0, 5013: 0, 5017: 0, 5021: 1, 5027: 0, 5030: 0, 5034: 0, 5037: 0, 5052: 0, 5053: 1, 5065: 0, 5070: 1, 5075: 1, 5082: 0, 5097: 0, 5105: 0, 5108: 0, 5115: 1, 5116: 1, 5119: 0, 5135: 1, 5144: 1, 5155: 0, 5158: 1, 5161: 1, 5163: 0, 5173: 0, 5181: 0, 5183: 1, 5185: 1, 5190: 0, 5192: 1, 5196: 0, 5199: 0, 5206: 0, 5210: 0, 5214: 0, 5215: 0, 5219: 0, 5227: 1, 5229: 0, 5231: 1, 5233: 0, 5240: 1, 5241: 0, 5252: 0, 5258: 0, 5267: 1, 5269: 0, 5275: 1, 5276: 0, 5284: 0, 5286: 1, 5287: 0, 5292: 1, 5298: 0, 5301: 0, 5310: 1, 5311: 0, 5313: 0, 5324: 0, 5328: 0, 5333: 0, 5341: 0, 5352: 1, 5355: 0, 5356: 0, 5378: 0, 5393: 0, 5398: 1, 5399: 0, 5401: 0, 5417: 1, 5426: 0, 5437: 0, 5439: 0, 5441: 0, 5450: 1, 5464: 1, 5466: 0, 5474: 0, 5477: 1, 5478: 0, 5483: 0, 5485: 0, 5497: 0, 5500: 0, 5502: 1, 5503: 1, 5504: 1, 5510: 0, 5518: 0, 5520: 0, 5521: 0, 5525: 0, 5532: 0, 5536: 0, 5539: 1, 5544: 1, 5548: 1, 5568: 0, 5575: 1, 5578: 0, 5581: 1, 5584: 0, 5587: 1, 5597: 0, 5607: 0, 5611: 1, 5613: 0, 5614: 0, 5626: 0, 5635: 1, 5637: 1, 5645: 1, 5647: 1, 5656: 1, 5658: 1, 5659: 0, 5662: 0, 5663: 0, 5664: 0, 5666: 1, 5667: 0, 5676: 0, 5679: 0, 5681: 0, 5682: 0, 5716: 0, 5717: 1, 5718: 0, 5724: 1, 5726: 1, 5728: 1, 5736: 1, 5739: 0, 5741: 0, 5755: 1, 5764: 0, 5766: 0, 5788: 0, 5793: 0, 5801: 0, 5808: 0, 5810: 0, 5819: 1, 5833: 0, 5836: 0, 5839: 0, 5840: 1, 5847: 0, 5849: 1, 5850: 1, 5853: 0, 5854: 1, 5866: 0, 5868: 0, 5874: 1, 5881: 0, 5886: 0, 5905: 1, 5910: 0, 5913: 1, 5921: 0, 5940: 1, 5942: 1, 5945: 0, 5946: 1, 5953: 0, 5959: 1, 5966: 0, 5970: 0, 5971: 1, 5977: 0, 5981: 1, 5991: 1, 5995: 1, 6002: 1, 6018: 0, 6019: 1, 6021: 0, 6023: 1, 6027: 0, 6034: 1, 6036: 1, 6037: 0, 6043: 1, 6048: 0, 6050: 1, 6059: 1, 6063: 1, 6065: 0, 6068: 0, 6070: 1, 6075: 0, 6087: 0, 6091: 0, 6094: 0, 6096: 1, 6097: 0, 6109: 1, 6110: 0, 6111: 0, 6115: 0, 6124: 0, 6126: 0, 6131: 0, 6140: 1, 6160: 0, 6170: 1, 6173: 0, 6179: 0, 6185: 0, 6188: 0, 6192: 1, 6193: 0, 6202: 0, 6204: 0, 6226: 1, 6229: 1, 6236: 0, 6241: 0, 6246: 0, 6248: 0, 6253: 1, 6254: 0, 6275: 0, 6287: 0, 6291: 1, 6294: 0, 6303: 1, 6310: 0, 6318: 0, 6323: 0, 6330: 0, 6338: 0, 6344: 1, 6354: 0, 6356: 1, 6365: 0, 6366: 0, 6370: 0, 6371: 0, 6373: 0, 6374: 0, 6377: 1, 6383: 0, 6396: 1, 6398: 1, 6419: 0, 6441: 0, 6444: 1, 6446: 0, 6458: 0, 6462: 0, 6485: 0, 6493: 0, 6516: 0, 6517: 1, 6523: 0, 6541: 0, 6548: 1, 6559: 1, 6564: 0, 6574: 0, 6581: 0, 6586: 0, 6594: 0, 6604: 1, 6609: 1, 6611: 1, 6623: 1, 6628: 0, 6637: 1, 6649: 0, 6650: 0, 6660: 1, 6671: 1, 6673: 1, 6680: 0, 6685: 0, 6706: 0, 6712: 0, 6714: 0, 6716: 0, 6743: 1, 6751: 0, 6754: 0, 6765: 0, 6770: 0, 6776: 1, 6784: 1, 6793: 1, 6810: 1, 6835: 1, 6846: 1, 6887: 0, 6911: 0, 6912: 1, 6925: 1, 6927: 0, 6934: 1, 6943: 0, 6946: 0, 6956: 1, 6966: 0, 6976: 0, 6982: 0, 6992: 1, 7005: 1, 7013: 1, 7016: 1, 7017: 1, 7022: 1, 7028: 1, 7032: 1, 7033: 1, 7041: 0, 7042: 0, 7048: 0, 7060: 1, 7064: 0, 7068: 1, 7070: 0, 7071: 0, 7083: 0, 7087: 0, 7092: 1, 7093: 1, 7094: 0, 7096: 0, 7099: 0, 7105: 0, 7112: 1, 7117: 0, 7118: 0, 7131: 0, 7140: 1, 7150: 0, 7151: 0, 7169: 1, 7173: 0, 7179: 0, 7188: 1, 7189: 0, 7198: 0, 7204: 0, 7221: 0, 7225: 0, 7238: 0, 7239: 0, 7263: 0, 7271: 0, 7278: 0, 7304: 0, 7308: 1, 7314: 0, 7349: 0, 7354: 0, 7367: 0, 7385: 0, 7391: 0, 7400: 0, 7405: 0, 7418: 0, 7429: 0, 7435: 0, 7451: 0, 7452: 0, 7473: 1, 7475: 1, 7486: 0, 7487: 0, 7499: 0, 7515: 1, 7534: 0, 7535: 0, 7553: 1, 7576: 0, 7578: 0, 7608: 0, 7610: 0, 7616: 1, 7618: 0, 7625: 1, 7644: 1, 7645: 0, 7654: 1, 7662: 0, 7663: 0, 7671: 0, 7680: 0, 7716: 0, 7741: 0, 7762: 0, 7794: 0, 7815: 1, 7840: 0, 7842: 0, 7851: 0, 7853: 0, 7877: 0, 7883: 0, 7888: 0, 7911: 0, 7915: 0, 7918: 1, 7927: 0, 7931: 0, 7949: 1, 7957: 1, 7960: 0, 7961: 1, 8016: 0, 8061: 1, 8085: 0, 8093: 1, 8135: 0, 8142: 1, 8163: 1, 8172: 0, 8182: 1, 8187: 0, 8206: 0, 8213: 1, 8214: 0, 8252: 1, 8254: 0, 8255: 0, 8272: 0, 8349: 1, 8367: 1, 8371: 0, 8391: 0, 8401: 1, 8420: 0, 8471: 0, 8472: 1, 8478: 0, 8493: 0, 8502: 0, 8507: 0, 8619: 0, 8620: 0, 8625: 0, 8647: 1, 8648: 1, 8649: 1, 8659: 1, 8669: 0, 8684: 1, 8721: 1, 8724: 1, 8727: 0, 8792: 1, 8820: 0, 8822: 0, 8823: 0, 8824: 0, 8840: 0, 8842: 0, 8848: 0, 8920: 1, 8935: 0, 8941: 0, 8960: 1, 8982: 0, 9013: 1, 9020: 0, 9053: 0, 9128: 0, 9131: 0, 9140: 0, 9149: 0, 9155: 0, 9169: 1, 9171: 0, 9180: 1, 9187: 0, 9189: 1, 9214: 1, 9225: 0, 9233: 1, 9235: 0, 9237: 0, 9244: 0, 9252: 0, 9293: 0, 9298: 1, 9360: 0, 9399: 0, 9423: 0, 9467: 0, 9472: 0, 9481: 0, 9488: 0, 9498: 0, 9511: 1, 9520: 0, 9534: 0, 9541: 1, 9548: 0, 9560: 0, 9563: 0, 9576: 1, 9578: 0, 9580: 0, 9606: 0, 9638: 0, 9653: 0, 9664: 0, 9683: 0, 9690: 1, 9720: 0, 9738: 1, 9740: 0, 9758: 0, 9768: 1, 9773: 1, 9780: 0, 9785: 1, 9789: 0, 9795: 1, 9809: 0, 9817: 0, 9821: 0, 9830: 0, 9869: 0, 9918: 0, 9926: 0, 9936: 0, 9948: 1, 9951: 1, 9963: 1, 9969: 0, 9999: 1, 10043: 0, 10086: 1, 10090: 0, 10202: 1, 10222: 1, 10231: 0, 10339: 1, 10374: 0, 10386: 1, 10388: 0, 10394: 0, 10399: 1, 10430: 0, 10484: 1, 10492: 1, 10620: 0, 10622: 0, 10640: 1, 10648: 0, 10655: 0, 10665: 1, 10703: 1, 10735: 1, 10759: 1, 10771: 0, 10787: 1, 10877: 0, 10909: 0, 10950: 0, 10970: 0, 10995: 0, 11015: 1, 11037: 1, 11069: 0, 11071: 1, 11097: 1, 11117: 1, 11123: 0, 11139: 0, 11162: 1, 11179: 1, 11180: 0, 11203: 1, 11211: 0, 11222: 0, 11228: 0, 11253: 0, 11269: 0, 11336: 0, 11373: 0, 11395: 1, 11411: 0, 11473: 0, 11484: 0, 11523: 0, 11645: 0, 11655: 0, 11663: 0, 11682: 0, 11684: 0, 11694: 0, 11696: 0, 11739: 0, 11806: 0, 11809: 0, 11875: 1, 11960: 1, 12008: 1, 12011: 0, 12015: 0, 12158: 0, 12205: 0, 12213: 0, 12237: 1, 12250: 1, 12251: 0, 12254: 0, 12286: 0, 12298: 0, 12308: 0, 12317: 0, 12318: 0, 12324: 0, 12373: 1, 12375: 1, 12407: 1, 12453: 0, 12467: 1, 12504: 0, 12526: 1, 12545: 1, 12647: 0, 12667: 0, 12720: 0, 12726: 1, 12779: 1, 12801: 1, 12854: 0, 12905: 0, 12937: 0, 12979: 0, 13008: 0, 13039: 1, 13044: 0, 13061: 0, 13074: 0, 13098: 0, 13099: 0, 13121: 1, 13134: 0, 13141: 0, 13146: 1, 13154: 1, 13158: 1, 13167: 0, 13170: 0, 13200: 1, 13209: 0, 13369: 0, 13464: 0, 13475: 0, 13506: 1, 13554: 1, 13597: 1, 13670: 0, 13676: 0, 13697: 0, 13785: 0, 13814: 0, 13817: 0, 13838: 1, 13955: 0, 13965: 0, 14110: 0, 14145: 0, 14146: 0, 14156: 0, 14169: 0, 14359: 0, 14406: 0, 14422: 0, 14456: 0, 14481: 1, 14495: 0, 14496: 0, 14505: 1, 14524: 0, 14555: 0, 14561: 1, 14576: 0, 14584: 1, 14591: 1, 14663: 0, 14729: 0, 14774: 0, 14783: 0, 14786: 1, 14788: 0, 14817: 0, 14958: 0, 14997: 0, 14998: 0, 15026: 0, 15038: 1, 15056: 0, 15061: 0, 15072: 0, 15107: 0, 15135: 0, 15183: 0, 15252: 0, 15262: 0, 15296: 1, 15305: 1, 15356: 1, 15372: 0, 15375: 1, 15394: 0, 15412: 0, 15426: 0, 15521: 0, 15550: 0, 15563: 0, 15605: 1, 15755: 1, 15867: 0, 15970: 0, 16003: 1, 16008: 0, 16028: 1, 16056: 0, 16067: 0, 16078: 0, 16116: 0, 16198: 0, 16222: 1, 16283: 1, 16297: 0, 16377: 1, 16438: 0, 16484: 0, 16517: 0, 16551: 0, 16578: 0, 16595: 0, 16606: 0, 16654: 0, 16750: 0, 16776: 0, 16790: 0, 16807: 0, 16829: 1, 16831: 1, 16833: 1, 16847: 0, 16879: 0, 16892: 0, 16983: 0, 17006: 0, 17012: 0, 17024: 0, 17174: 1, 17201: 0, 17269: 0, 17330: 0, 17342: 1, 17382: 1, 17385: 0, 17408: 0, 17436: 1, 17473: 1, 17605: 0, 17704: 1, 17743: 1, 17858: 0, 17897: 0, 17909: 0, 17961: 0, 18082: 1, 18096: 0, 18147: 0, 18201: 0, 18343: 0, 18498: 0, 18501: 0, 18562: 0, 18572: 0, 18623: 0, 18685: 0, 18752: 0, 18777: 0, 18784: 0, 18802: 0, 18858: 0, 18862: 0, 18880: 0, 18891: 0, 18905: 0, 18910: 0, 18964: 1, 18981: 0, 19154: 1, 19155: 0, 19194: 0, 19254: 0, 19266: 0, 19273: 0, 19286: 0, 19325: 0, 19378: 0, 19418: 0, 19437: 0, 19508: 0, 19613: 0, 19669: 1, 19693: 0, 19843: 0, 19855: 0, 19859: 0, 19865: 1, 19926: 0, 19981: 0, 20004: 0, 20026: 0, 20037: 0, 20043: 0, 20058: 1, 20150: 0, 20204: 1, 20235: 0, 20262: 0, 20282: 1, 20382: 0, 20424: 0, 20453: 0, 20471: 1, 20495: 0, 20534: 0, 20663: 0, 20709: 0, 20759: 1, 20768: 0, 20772: 0, 20848: 0, 20874: 0, 20897: 0, 20908: 0, 20930: 0, 20969: 1, 21024: 0, 21170: 0, 21236: 0, 21352: 0, 21359: 0, 21442: 0, 21481: 0, 21537: 1, 21643: 0, 21697: 0, 21701: 1, 21909: 0, 22010: 0, 22033: 1, 22157: 0, 22182: 0, 22225: 0, 22296: 0, 22399: 1, 22432: 0, 22592: 0, 22612: 0, 22631: 1, 22705: 1, 22764: 1, 22794: 0, 22816: 0, 22820: 1, 22896: 0, 23075: 0, 23105: 0, 23178: 0, 23242: 0, 23274: 0, 23305: 0, 23320: 0, 23453: 1, 23458: 0, 23552: 0, 23615: 0, 23690: 0, 23714: 0, 23882: 0, 24008: 0, 24076: 1, 24131: 0, 24161: 0, 24467: 0, 24587: 1, 24691: 0, 24877: 0, 24969: 0, 25151: 0, 25186: 0, 25357: 0, 25394: 0, 25398: 0, 25420: 0, 25535: 0, 25541: 0, 25620: 0, 25763: 0, 25851: 0, 25926: 0, 25938: 0, 25949: 0, 26133: 0, 26165: 0, 26218: 0, 26317: 1, 26349: 1, 26390: 0, 26695: 1, 26744: 0, 26843: 0, 27003: 0, 27284: 1, 27387: 0, 27431: 0, 27437: 0, 27479: 0, 27590: 0, 27625: 0, 27710: 0, 27880: 0, 27921: 0, 27924: 1, 27925: 0, 28189: 0, 28226: 0, 28342: 0, 28581: 0, 28617: 0, 28661: 0, 29025: 0, 29038: 0, 29040: 1, 29060: 1, 29256: 1, 29519: 0, 29558: 0, 29617: 0, 29845: 0, 29969: 0, 29970: 1, 30295: 0, 30305: 0, 30406: 0, 30421: 1, 30661: 0, 30698: 0, 31003: 0, 31168: 0, 31169: 0, 31329: 0, 31405: 0, 31448: 0, 31585: 0, 31606: 0, 31854: 0, 31928: 0, 31939: 0, 31997: 0, 32045: 0, 32101: 0, 32634: 0, 32636: 0, 33041: 0, 33678: 0, 33684: 0, 33794: 1, 33804: 0, 33981: 0, 34004: 0, 34175: 0, 34210: 0, 34219: 0, 34266: 0, 34578: 0, 34760: 1, 34797: 0, 34801: 0, 34933: 0, 34977: 0, 35029: 0, 35263: 0, 35270: 0, 35351: 1, 35424: 1, 35618: 0, 35820: 0, 35970: 0, 36120: 0, 36138: 0, 36337: 0, 36346: 0, 36415: 0, 36503: 0, 36558: 0, 37200: 0, 37536: 0, 38699: 0, 39208: 0, 39316: 0, 39358: 0, 39815: 0, 39853: 0, 40021: 0, 40280: 0, 40400: 0, 40645: 0, 40713: 0, 40901: 0, 41045: 1, 41302: 0, 41705: 0, 42790: 0, 42805: 0, 43074: 1, 43212: 0, 43229: 0, 43342: 0, 43620: 1, 43752: 0, 43828: 0, 44262: 0, 44964: 0, 45259: 0, 45595: 0, 45710: 0, 45938: 0, 46082: 1, 46201: 1, 46412: 0, 47847: 0, 48128: 0, 48342: 0, 48710: 0, 49130: 0, 49179: 0, 50076: 0, 50284: 0, 50332: 1, 50660: 0, 51552: 1, 52165: 0, 52302: 0, 52667: 0, 53056: 0, 53334: 1, 54337: 0, 54821: 0, 55333: 0, 55482: 0, 55489: 1, 55563: 0, 55711: 0, 56020: 0, 56269: 0, 56358: 0, 57392: 0, 57551: 0, 58149: 0, 58323: 1, 59825: 0, 59832: 0, 60106: 1, 60481: 0, 60824: 0, 60920: 1, 61257: 0, 61472: 0, 62422: 0, 64078: 0, 64692: 0, 64992: 0, 65366: 0, 66767: 0, 67493: 0, 67803: 0, 67928: 0, 68828: 0, 69294: 0, 69810: 0, 70066: 0, 70222: 0, 70664: 0, 71625: 0, 72072: 0, 72199: 0, 73670: 0, 74106: 1, 74883: 0, 75372: 0, 75527: 0, 76523: 0, 77248: 0, 77574: 0, 78706: 0, 81124: 0, 82342: 0, 82752: 0, 82954: 1, 84161: 0, 84488: 0, 85957: 1, 87431: 0, 87439: 0, 88412: 0, 89455: 0, 91438: 1, 95980: 0, 97745: 0, 98928: 0, 99321: 0, 99866: 0, 100623: 0, 101498: 0, 104659: 0, 108062: 0, 110424: 0, 112489: 0, 113966: 0, 125330: 0, 131156: 0, 132395: 0, 132652: 0, 138087: 0, 143765: 0, 148737: 0, 153791: 0, 157508: 0, 162767: 0, 163897: 0, 165682: 0, 166880: 0, 169515: 0, 170653: 0, 179140: 0, 189967: 0, 190087: 0, 194675: 0}


In [131]:
DIC_PATH = f'data/crosslingual/dictionaries/{src_lang}-{tgt_lang}.5000-6500.txt'
s_t_dict = pd.read_csv(DIC_PATH, sep='\t',header=None)
DIC_PATH = f'data/crosslingual/dictionaries/{src_lang}-{mid_lang}.5000-6500.txt'
s_m_dict = pd.read_csv(DIC_PATH, sep=' ',header=None)
DIC_PATH = f'data/crosslingual/dictionaries/{mid_lang}-{tgt_lang}.5000-6500.txt'
m_t_dict = pd.read_csv(DIC_PATH, sep='\t',header=None)

따로 학습된 맵핑을 곱해서.. 다이랙트 맵핑이랑 비교해보기

In [132]:
# s_t_reload(wikivec_src[source_word].to(mapping.weight.device)).to(input_emb.device)
s_m_dict

0              1
0              kiev           kyiv
1              kiev           kiev
2               sac            bag
3             flûte          flute
4            arabie         arabia
...             ...            ...
2337      violation   infringement
2338  conservateurs  preservatives
2339  conservateurs  conservatives
2340  conservateurs       curators
2341  conservateurs   conservative

[2342 rows x 2 columns]

In [35]:
source_we = wikivec_src.index2word[3593]
source_we

'rythme'

In [134]:
for word in [3593]:
    source_word = wikivec_src.index2word[word]
    print(source_word)
#     s_to_m = wikivec_src[wikivec_src.index2word[3593]].dot(s_m_reload)
#     m_to_t = s_to_m.dot(m_t_reload)
#     expect_words = [x[0] for x in fastvec_tgt.most_similar(positive=[s_to_t], topn=10)]
    expect = wikivec_src[source_word].dot(s_m_reload)
    expect_words = [wikivec_mid.most_similar(positive=[expect], topn=20)]
    print(expect_words)

rythme
[[('chico', 0.22705423831939697), ('ferny', 0.2240215241909027), ('righetti', 0.21532955765724182), ('filson', 0.21202075481414795), ('alyn', 0.21159055829048157), ('ENTITY/Jack_Webb', 0.21030913293361664), ('ENTITY/Miranda_(state)', 0.20946063101291656), ('carril', 0.20826590061187744), ('pulaski', 0.2082509994506836), ('ENTITY/Georges_Simenon', 0.20810794830322266), ('ENTITY/Vinnie_Colaiuta', 0.20656588673591614), ('proviso', 0.20447997748851776), ('baile', 0.20375938713550568), ('ENTITY/Victor_Hugo', 0.20282921195030212), ('felis', 0.202504962682724), ('ashbrook', 0.20185931026935577), ('marquis', 0.2011902928352356), ('toren', 0.20055505633354187), ('elba', 0.20036067068576813), ('kaskaskia', 0.19980330765247345)]]


In [38]:
wikivec_src.index2word[3593]

TypeError: 'int' object is not iterable

In [119]:
s_t_reload

tensor([[ 0.0830,  0.0644,  0.0031,  ...,  0.0434,  0.0232, -0.0072],
        [-0.0134, -0.0504,  0.0066,  ..., -0.0345,  0.1439,  0.0103],
        [ 0.0433,  0.0218,  0.0992,  ..., -0.0914, -0.0626,  0.0035],
        ...,
        [ 0.0832,  0.0201, -0.0218,  ..., -0.0602, -0.0499, -0.0071],
        [ 0.0020, -0.0943, -0.0328,  ...,  0.0405,  0.0659,  0.0500],
        [-0.0072, -0.0967, -0.0288,  ..., -0.0034,  0.0499, -0.0266]])

In [125]:
input1

tensor([[ 0.0028, -0.0090, -0.0073,  ...,  0.0095, -0.0065, -0.0251],
        [ 0.0198, -0.0444,  0.0189,  ..., -0.0149, -0.0024, -0.0138],
        [-0.0618, -0.0584, -0.0426,  ..., -0.0158,  0.0998, -0.0471],
        ...,
        [-0.0116,  0.0435,  0.0609,  ...,  0.0468, -0.0102, -0.0056],
        [-0.0289,  0.0090,  0.0300,  ...,  0.0082,  0.0107,  0.0329],
        [ 0.0004,  0.0458,  0.0302,  ...,  0.0139,  0.0353, -0.0800]])

In [126]:
input2

tensor([[-0.0606, -0.0587, -0.0356,  ..., -0.0138, -0.0536, -0.0125],
        [ 0.0372, -0.0142, -0.0096,  ..., -0.0112,  0.0433,  0.0811],
        [-0.0124,  0.0002, -0.0170,  ...,  0.0581,  0.0442, -0.0450],
        ...,
        [ 0.0511, -0.0222,  0.0152,  ...,  0.0507, -0.0244,  0.0144],
        [-0.0322,  0.0175, -0.0106,  ..., -0.0522,  0.0168, -0.0273],
        [ 0.0163, -0.0553,  0.0329,  ...,  0.0088,  0.0063,  0.0223]])

In [127]:
input3

tensor([[ 0.0245,  0.0737,  0.0174,  ...,  0.0342,  0.0151, -0.0275],
        [-0.0201, -0.0445,  0.0454,  ..., -0.0073,  0.1393,  0.0041],
        [ 0.0150, -0.0463,  0.0609,  ..., -0.0199, -0.0507, -0.0157],
        ...,
        [ 0.0614, -0.0207,  0.0082,  ..., -0.0246, -0.0614,  0.0018],
        [ 0.0105, -0.0625,  0.0019,  ...,  0.0226,  0.1041,  0.0135],
        [-0.0515, -0.0843, -0.0512,  ...,  0.0590, -0.0135,  0.0145]])

In [128]:
input4

tensor([[-0.0606,  0.0372, -0.0124,  ...,  0.0511, -0.0322,  0.0163],
        [-0.0587, -0.0142,  0.0002,  ..., -0.0222,  0.0175, -0.0553],
        [-0.0356, -0.0096, -0.0170,  ...,  0.0152, -0.0106,  0.0329],
        ...,
        [-0.0138, -0.0112,  0.0581,  ...,  0.0507, -0.0522,  0.0088],
        [-0.0536,  0.0433,  0.0442,  ..., -0.0244,  0.0168,  0.0063],
        [-0.0125,  0.0811, -0.0450,  ...,  0.0144, -0.0273,  0.0223]])

In [124]:
input1 = s_m_reload.matmul(m_t_reload)
input2 = s_m_reload.matmul(torch.transpose(m_t_reload,0,1))
input3 = m_t_reload.matmul(s_m_reload)
input4 = m_t_reload.matmul(torch.transpose(s_m_reload,0,1))

In [121]:
input3 = s_m_reload.matmul(torch.transpose(m_t_reload,0,1))

In [123]:
help(s_m_reload.to)

Help on built-in function to:

to(...) method of torch.Tensor instance
    to(*args, **kwargs) -> Tensor
    
    Performs Tensor dtype and/or device conversion. A :class:`torch.dtype` and :class:`torch.device` are
    inferred from the arguments of ``self.to(*args, **kwargs)``.
    
    .. note::
    
        If the ``self`` Tensor already
        has the correct :class:`torch.dtype` and :class:`torch.device`, then ``self`` is returned.
        Otherwise, the returned tensor is a copy of ``self`` with the desired
        :class:`torch.dtype` and :class:`torch.device`.
    
    Here are the ways to call ``to``:
    
    .. function:: to(dtype, non_blocking=False, copy=False, memory_format=torch.preserve_format) -> Tensor
    
        Returns a Tensor with the specified :attr:`dtype`
    
        Args:
            memory_format (:class:`torch.memory_format`, optional): the desired memory format of
            returned Tensor. Default: ``torch.preserve_format``.
    
    .. function:: to

In [17]:
cos = torch.nn.CosineSimilarity(dim=1, eps=1e-6)

In [120]:
torch.save(input3.cpu().detach().numpy(), f'debug_file/debug/evaluate_{src_lang}_{mid_lang}_{tgt_lang.upper()}/best_mapping_{src_lang}2{tgt_lang}_3.t7')

In [115]:
torch.save(input2.cpu().detach().numpy(), f'debug_file/debug/evaluate_{src_lang}_{mid_lang}_{tgt_lang.upper()}/best_mapping_{src_lang}2{tgt_lang}_2.t7')

In [105]:
temp.round(3)

array([-0.049, -0.05 ,  0.053,  0.02 , -0.025,  0.031,  0.052, -0.036,
       -0.009,  0.038, -0.011,  0.129,  0.003,  0.049,  0.067, -0.01 ,
        0.038, -0.038, -0.026,  0.027,  0.012, -0.017,  0.068,  0.021,
       -0.046,  0.047, -0.057,  0.053, -0.033,  0.077,  0.035, -0.091,
        0.056,  0.066, -0.006, -0.069, -0.002,  0.047,  0.006, -0.057,
        0.046,  0.02 ,  0.005, -0.044,  0.01 ,  0.093,  0.059,  0.017,
        0.054, -0.037, -0.091,  0.066,  0.129,  0.003,  0.008,  0.009,
        0.022,  0.016, -0.03 , -0.044,  0.037,  0.04 , -0.061, -0.023,
       -0.025,  0.011, -0.12 , -0.064,  0.026,  0.072, -0.09 , -0.067,
       -0.014,  0.044,  0.007, -0.006,  0.044, -0.025, -0.08 ,  0.056,
        0.004,  0.128,  0.11 , -0.003, -0.046, -0.006,  0.024, -0.007,
       -0.045, -0.024, -0.077, -0.031,  0.017, -0.072,  0.024,  0.035,
       -0.071,  0.026, -0.02 ,  0.021,  0.038,  0.041,  0.072,  0.05 ,
        0.184, -0.11 , -0.02 , -0.05 ,  0.061,  0.022,  0.006, -0.039,
      

In [262]:
total_dict = [key for key in f_e_j_iden.keys() if key < 200000]
th_e_dict = [key for key, val in f_e_j_iden.items() if val > 0]
direct_dict = [key for key, val in f_j_iden.items() if val > 0]
inter_dict = list(set(th_e_dict) & set(direct_dict))

In [295]:
for t in inter_dict[:1] :
    temp = torch.from_numpy(fastvec_src[fastvec_src.index2word[1]])
    print(torch.mv(s_t_reload,temp))
    s_m = torch.mv(s_m_reload,temp)
    print(torch.mv(m_t_reload,s_m))

tensor([-4.9801e-03,  1.2935e-02, -5.5649e-02,  8.3878e-04,  5.5845e-02,
        -1.5110e-01,  6.2779e-02,  3.4610e-02, -2.4340e-01,  1.2397e-01,
         1.1477e-01, -3.8546e-02,  8.6529e-02,  3.0198e-01,  8.0160e-02,
         1.7052e-01, -3.4125e-02,  1.3796e-01,  3.4644e-02, -1.7205e-02,
        -1.6168e-01,  1.1051e-01,  2.1199e-03, -1.7337e-01,  9.5507e-02,
        -1.2696e-01, -9.2573e-03,  1.2359e-01,  1.1456e-01,  7.0156e-02,
        -1.2144e-01,  1.5215e-01, -3.2279e-02, -2.0904e-01, -1.8074e-01,
         2.0717e-01, -7.1795e-02,  2.6967e-01, -2.9745e-01,  1.8309e-01,
        -8.5748e-02, -1.5776e-01,  9.2821e-02, -3.2069e-02, -2.0665e-02,
        -1.1693e-02, -5.5051e-02,  1.5162e-01,  1.8202e-02, -6.5878e-02,
        -6.7465e-02,  1.5461e-02, -2.7502e-01,  7.1644e-02, -2.2201e-02,
         2.3515e-01, -6.9591e-02,  1.8941e-01,  1.4552e-01, -6.9848e-02,
         6.1258e-02, -7.5085e-02,  1.3928e-01,  2.1364e-01, -2.4052e-01,
        -1.1618e-01,  7.3290e-02,  4.8690e-02, -4.4

In [230]:
s_m_reload.(m_t_reload)

tensor([[ 0.0034, -0.0183, -0.0155,  ...,  0.0067,  0.0174, -0.0232],
        [ 0.0552, -0.0469,  0.0096,  ..., -0.0052, -0.0094, -0.0231],
        [-0.0710, -0.0675, -0.0595,  ..., -0.0251,  0.1001, -0.0422],
        ...,
        [-0.0347,  0.0470,  0.0588,  ...,  0.0550, -0.0019,  0.0010],
        [-0.0277,  0.0138,  0.0384,  ...,  0.0089, -0.0054,  0.0127],
        [ 0.0019,  0.0496,  0.0200,  ...,  0.0186,  0.0304, -0.0898]])

In [283]:
t = torch.from_numpy(fastvec_src[fastvec_src.index2word[1]])

In [284]:
t

tensor([ 0.0073,  0.1306,  0.1368,  0.0847, -0.0460,  0.0871, -0.1130, -0.0216,
         0.2906, -0.2475,  0.1587, -0.3387, -0.1674, -0.0465,  0.1284,  0.0855,
        -0.0129,  0.2162,  0.1144, -0.0642, -0.0375, -0.1368, -0.0156,  0.0798,
        -0.0083, -0.0169,  0.2961, -0.0564, -0.2164,  0.0316,  0.0274, -0.0257,
        -0.0207, -0.2404,  0.1065,  0.4204,  0.3065, -0.3154,  0.2699,  0.0342,
         0.1598, -0.1666,  0.2131, -0.0881,  0.2226,  0.0474,  0.1413,  0.0551,
        -0.0725,  0.2702, -0.1112,  0.0504, -0.2157, -0.0442, -0.0848, -0.1682,
         0.1534,  0.0570, -0.1962, -0.0703, -0.2339,  0.0713,  0.1488, -0.1264,
        -0.1516,  0.0102, -0.0775, -0.1822,  0.2502, -0.1345,  0.0219, -0.1281,
        -0.2484,  0.0747, -0.2142,  0.2655, -0.0423, -0.2179, -0.2225,  0.0396,
         0.0326,  0.2674, -0.1119, -0.1017,  0.0622, -0.1920, -0.1144,  0.1885,
         0.0566,  0.2218,  0.4336,  0.0396, -0.3682, -0.0497, -0.4156,  0.1409,
         0.1715, -0.1628,  0.0600,  0.09

In [285]:
fastvec_src[fastvec_src.index2word[1]]

array([ 0.0073,  0.1306,  0.1368,  0.0847, -0.046 ,  0.0871, -0.113 ,
       -0.0216,  0.2906, -0.2475,  0.1587, -0.3387, -0.1674, -0.0465,
        0.1284,  0.0855, -0.0129,  0.2162,  0.1144, -0.0642, -0.0375,
       -0.1368, -0.0156,  0.0798, -0.0083, -0.0169,  0.2961, -0.0564,
       -0.2164,  0.0316,  0.0274, -0.0257, -0.0207, -0.2404,  0.1065,
        0.4204,  0.3065, -0.3154,  0.2699,  0.0342,  0.1598, -0.1666,
        0.2131, -0.0881,  0.2226,  0.0474,  0.1413,  0.0551, -0.0725,
        0.2702, -0.1112,  0.0504, -0.2157, -0.0442, -0.0848, -0.1682,
        0.1534,  0.057 , -0.1962, -0.0703, -0.2339,  0.0713,  0.1488,
       -0.1264, -0.1516,  0.0102, -0.0775, -0.1822,  0.2502, -0.1345,
        0.0219, -0.1281, -0.2484,  0.0747, -0.2142,  0.2655, -0.0423,
       -0.2179, -0.2225,  0.0396,  0.0326,  0.2674, -0.1119, -0.1017,
        0.0622, -0.192 , -0.1144,  0.1885,  0.0566,  0.2218,  0.4336,
        0.0396, -0.3682, -0.0497, -0.4156,  0.1409,  0.1715, -0.1628,
        0.06  ,  0.0

In [130]:
s_w2v = list(fastvec_src.wv.vocab)
t_w2v = list(fastvec_tgt.wv.vocab)
m_w2v = list(fastvec_mid.wv.vocab)

<ipython-input-130-c798f4072518>:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  s_w2v = list(fastvec_src.wv.vocab)
<ipython-input-130-c798f4072518>:2: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  t_w2v = list(fastvec_tgt.wv.vocab)
<ipython-input-130-c798f4072518>:3: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  m_w2v = list(fastvec_mid.wv.vocab)


In [193]:
s_words = s_m_dict[0].unique().tolist()
s_words = list(set(s_words).intersection(set(s_w2v)))
m_words = m_t_dict[0].unique().tolist()
m_words = list(set(m_words).intersection(set(m_w2v)))

In [191]:
for word in s_words:
    s_to_m = fastvec_src[word].dot(s_m_reload)
#     print('Source word :', word)
    dict_words = s_m_dict[s_m_dict[0]==word][1].values
#     print('Dictionary Pairs :')
#     print(dict_words)
    expect_words = [x[0] for x in fastvec_mid.most_similar(positive=[s_to_m], topn=100)]
#     expect_words = [fastvec_tgt.most_similar(positive=[s_to_m], topn=10)]
#     print('Expected Most Similar Pairs :')
#     print(expect_words)
    if len(set(dict_words)&set(expect_words)) > 0:
        print(set(dict_words)&set(expect_words))
print(len(s_words))


{'scandal'}
{'uniforms'}
{'strictly'}
{'authorized'}
{'route'}
{'receipts'}
{'adopt'}
{'wild'}
{'expenses'}
{'estimated'}
1455


In [194]:
for word in m_words:
    m_to_t = fastvec_mid[word].dot(m_t_reload)
#     print('Source word :', word)
    dict_words = m_t_dict[m_t_dict[0]==word][1].values
#     print('Dictionary Pairs :')
#     print(dict_words)
    expect_words = [x[0] for x in fastvec_tgt.most_similar(positive=[m_to_t], topn=100)]
#     expect_words = [fastvec_tgt.most_similar(positive=[s_to_m], topn=10)]
#     print('Expected Most Similar Pairs :')
#     print(expect_words)
    if len(set(dict_words)&set(expect_words)) > 0:
        print(set(dict_words)&set(expect_words))
print(len(m_words))


{'特権'}
{'検出'}
{'高地'}
{'セクター'}
{'ムード'}
1425


In [195]:
for word in s_words:
    s_to_t = fastvec_src[word].dot(s_t_reload)
#     print('Source word :', word)
    dict_words = s_t_dict[s_t_dict[0]==word][1].values
#     print('Dictionary Pairs :')
#     print(dict_words)
    expect_words = [x[0] for x in fastvec_tgt.most_similar(positive=[s_to_t], topn=100)]
#     expect_words = [fastvec_tgt.most_similar(positive=[s_to_m], topn=10)]
#     print('Expected Most Similar Pairs :')
#     print(expect_words)
    if len(set(dict_words)&set(expect_words)) > 0:
        print(set(dict_words)&set(expect_words))
print(len(m_words))


{'最近'}
{'野生'}
1425


In [151]:
for word in s_words[:10]:
    s_to_m = fastvec_src[word].dot(s_m_reload)
    m_to_t = s_to_m.dot(m_t_reload)
    print(word)
    dict_words = s_t_dict[s_t_dict[0]==word][1].values
    print(dict_words)
#     expect_words = [x[0] for x in fastvec_tgt.most_similar(positive=[s_to_t], topn=10)]
    expect_words = [fastvec_tgt.most_similar(positive=[m_to_t], topn=10)]
    print(expect_words)

accords
['協定']
[[('爬虫類', 0.21161669492721558), ('ENTITY/哺乳類', 0.21142099797725677), ('象', 0.20770415663719177), ('しょう', 0.20003186166286469), ('錦', 0.1954100877046585), ('市政', 0.19538061320781708), ('拠れ', 0.18767963349819183), ('隆', 0.18737435340881348), ('哺乳類', 0.1829044371843338), ('水木', 0.17866824567317963)]]
permission
['許可' '許諾']
[[('@', 0.2737450897693634), ('live', 0.2326582670211792), ('ENTITY/竹書房', 0.23168043792247772), ('社会学部', 0.22639751434326172), ('＠', 0.22536657750606537), ('紀要', 0.22412054240703583), ('新宿', 0.21390904486179352), ('”', 0.2125556766986847), ('あさ', 0.2115757018327713), ('anniversary', 0.21116848289966583)]]
surpris
['驚き' 'サプライズ']
[[('時', 0.2325102686882019), ('付近', 0.22179707884788513), ('筑紫', 0.2178540825843811), ('南東', 0.2175218015909195), ('西端', 0.21682991087436676), ('回数', 0.21518807113170624), ('南西', 0.21302036941051483), ('北西', 0.20989349484443665), ('th', 0.2088238000869751), ('ENTITY/近畿日本鉄道', 0.20809657871723175)]]
dispositifs
['デバイス' '機器']
[[('シアター

In [152]:
for word in sm_words[:10]:
    s_to_m = fastvec_src[word].dot(s_m_reload)

    print(word)
    dict_words = s_m_dict[s_m_dict[0]==word][1].values
    print(dict_words)
#     expect_words = [x[0] for x in fastvec_tgt.most_similar(positive=[s_to_t], topn=10)]
    expect_words = [fastvec_mid.most_similar(positive=[s_to_m], topn=10)]
    print(expect_words)

nominations
['appointments' 'nominations']
[[('antagonist', 0.21882085502147675), ('ENTITY/Drama', 0.2116265743970871), ('potomac', 0.20722389221191406), ('mutant', 0.19629399478435516), ('frost', 0.1960476189851761), ('alter', 0.18892206251621246), ('copyright', 0.187873974442482), ('whitman', 0.18623819947242737), ('ENTITY/Himalayas', 0.18590661883354187), ('nervous', 0.18199104070663452)]]
démographie
['demographics' 'demography']
[[('ENTITY/Infantry', 0.1646169275045395), ('ENTITY/Prussia', 0.154950350522995), ('swords', 0.15463431179523468), ('decorations', 0.15262529253959656), ('cannons', 0.1485292911529541), ('del', 0.14794975519180298), ('chile', 0.14546626806259155), ('gun', 0.14479929208755493), ('rounds', 0.1401229053735733), ('armor', 0.13972344994544983)]]
peugeot
['peugeot']
[[('archbishops', 0.2068697065114975), ('feudal', 0.1945798397064209), ('rulers', 0.19323234260082245), ('monarchs', 0.18865443766117096), ('nominally', 0.18589217960834503), ('rites', 0.185184910893

In [168]:
word = '1795'
s_to_t = fastvec_src[word].dot(s_t_reload)
print('Source word :', word)
dict_words = s_t_dict[s_t_dict[0]==word][1].values
print('Dictionary Pairs :')
print(dict_words)
expect_words = [x[0] for x in fastvec_tgt.most_similar(positive=[s_to_t], topn=10)]
# expect_words = [fastvec_tgt.most_similar(positive=[s_to_t], topn=10)]
print('Expected Most Similar Pairs :')
print(expect_words)
print()

Source word : 1795
Dictionary Pairs :
[]
Expected Most Similar Pairs :
['刃物', 'ロボット', '左衛門', 'uefa', '伊賀', 'ハンマー', '惣', 'つり', '加わり', 'カップ']



In [196]:
fastvec_t = KeyedVectors.load_word2vec_format("debug_file/debug/test_identical_fr_EN_wiki2vec/vectors-fr.txt", limit=20000)

In [215]:
s_m_path

'debug_file/debug/test_identical_fr_EN_wiki2vec/best_mapping_fr2en.t7'

In [211]:
for t in temp:
    print(fastvec_src[t].dot(s_m_reload))
    print(fastvec_t[t])

[ 0.22569636  0.16956535 -0.09479279  0.02079241 -0.09501565 -0.12426118
  0.051757    0.01748578  0.0527786  -0.10448889 -0.06409888 -0.07317121
  0.05560346  0.04414085  0.222905    0.14506778  0.08270201 -0.12745772
 -0.17675681  0.17695007 -0.05863749  0.15360962  0.02390322  0.06031662
  0.14398988 -0.19519684 -0.09177887  0.01025968  0.05374993 -0.06709824
 -0.07929242 -0.03326946 -0.03825728  0.10483905  0.04923034 -0.18874614
  0.14862126  0.22414313  0.21310163  0.02019339  0.01668665 -0.07391916
  0.23852454 -0.05550843  0.1016321  -0.02996362 -0.23944236 -0.29040128
  0.03866068 -0.194952   -0.01588513  0.11410727 -0.03567482 -0.01194585
 -0.19927225  0.05490968 -0.24019058  0.02791069 -0.16528171 -0.00999104
  0.01947431  0.11899279 -0.03456143  0.04281282 -0.024622    0.28320876
 -0.04907064 -0.10415801 -0.09089147 -0.02416017 -0.06127374 -0.07300717
  0.23035924  0.08746991  0.11766403  0.01852573 -0.08253765  0.13716815
  0.10850154 -0.06863362  0.16256636  0.0261801  -0